<?php
/**
 * @var Dotdigitalgroup\Enterprise\Block\DotdigitalForm $block
 * @var Magento\Framework\Escaper $escaper
 */
?>
<script>
    require.config({
        config: {
            'Dotdigitalgroup_PageBuilder/js/content-type/dotdigitalgroup-form/preview': {
                isDDGEnabled: '<?= $escaper->escapeJs($block->isEnabled()); ?>',
                apiErrorMessage: '<?= $escaper->escapeJs($block->getActivationMessage()); ?>',
                ddgFormDataUrl: '<?= $escaper->escapeUrl(
                    $block->getUrl('dotdigitalgroup_pagebuilder/ajax/formdata')
                ); ?>'
            },
            'Dotdigitalgroup_Enterprise/js/form/element/form-select': {
                ddgFormOptionsUrl: '<?= $escaper->escapeUrl(
                    $block->getUrl('dotdigitalgroup_pagebuilder/ajax/formoptions')
                ); ?>'
            },
        }
    });
</script>
